version: "3.9"
services:
  database-mongo:
    # Mongo 5 does not work on Apple M1 chips
    image: mongo:4
    hostname: "mongo-db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: tpfinaldb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodata:/data/db
    # Make other containers not start until this one finishes starting
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo database-mongo:27017/tpfinaldb --quiet
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
  web_app_mongo:
    build: "./tpfinal"
    entrypoint: /entrypoint.sh
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8081"
    depends_on:
      database-mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: "on-failure"
  swagger-ui:
    # image: swaggerapi/swagger-ui
    # platform: linux/amd64
    image: pentusha/swagger-ui-crossbuild
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./doc/openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml

volumes:
  mongodata:
    driver: local