# Generated by Django 3.2.9 on 2022-02-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderstatus_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historic_prices', to='api.product'),
        ),
    ]
