# Generated by Django 3.2.9 on 2022-02-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_historicalproductprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='commentary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
