# Generated by Django 3.2.9 on 2022-02-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rating_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='api.order'),
            preserve_default=False,
        ),
    ]
